export const ENDPOINTS = {
  REGISTRATION: '/users/register',
  LOGIN: '/users/login',
  PROFILE: '/users/profile',
  INTERESTS: '/users/interests',
  UPDATE_SUBSCRIBERS: '/users/update/subscribers',
  USERS: '/users/all',
  CREATE_SONG: '/songs/create',
  CREATE_PLAYLIST: '/playlists/create',
  ADD_SONG_TO_PLAYLIST: '/playlists/add/song',
  GET_MY_PLAYLIST: '/playlists/my',
  GET_RECOMMEND_PLAYLISTS_GENRES: '/recommendation/playlists/genres',
  GET_RECOMMEND_PLAYLISTS_AUTHORS: '/recommendation/playlists/authors',
  GET_RECOMMEND_SONGS_GENRES: '/recommendation/songs/genres',
  GET_RECOMMEND_SONGS_AUTHORS: '/recommendation/songs/authors',
  GET_RECOMMEND_SONGS_RANDOM: '/recommendation/songs/random',
  GET_POPULAR_SONGS: '/recommendation/songs/popular',
  GET_POPULAR_AUTHORS: '/recommendation/authors/popular',
  GET_POPULAR_PLAYLISTS: '/recommendation/playlists/popular',
  GET_DATA_BY_SEARCH: '/recommendation/search',
  GET_ARTISTS: (genres: string[]) => `/songs/genres/artists?genres=${genres.join(',')}`,
  GET_SONGS: (username: string) => `/songs/all/${username}`,
  GET_PLAYLIST: (username: string) => `/playlists/get/${username}`,
  GET_PLAYLIST_BY_ID: (id: string) => `/playlists/${id}`,
  GET_MY_PLAYLIST_BY_ID: (id: string) => `/playlists/my/${id}`,
  GET_SONG: (id: string) => `/songs/${id}`,
  UPDATE_SONG_LIKE: (id: string) => `/songs/like/${id}`,
  UPDATE_SONG_DISLIKE: (id: string) => `/songs/dislike/${id}`,
  UPDATE_PLAYLIST_LIKE: (id: string) => `/playlists/like/${id}`,
  UPDATE_PLAYLIST_DISLIKE: (id: string) => `/playlists/dislike/${id}`,
  UPDATE_PLAYLIST: (id: string) => `/playlists/update/${id}`,
  UPDATE_SONG: (id: string) => `/songs/update/${id}`,
  USERS_INFO: (username: string) => `/users/info/${username}`,
  DELETE_SONG: (id: string) => `/songs/${id}`,
  DELETE_PLAYLIST: (id: string) => `/playlists/${id}`,
}
