export const ENDPOINTS = {
  REGISTRATION: '/users/register',
  LOGIN: '/users/login',
  PROFILE: '/users/profile',
  INTERESTS: '/users/interests',
  UPDATE_SUBSCRIBERS: '/users/update/subscribers',
  USERS: '/users/all',
  CREATE_SONG: '/songs/create',
  CREATE_PLAYLIST: '/playlists/create',
  GET_MY_PLAYLIST: '/playlists/my',
  GET_ARTISTS: (genres: string[]) => `/songs/genres/artists?genres=${genres.join(',')}`,
  GET_SONGS: (username: string) => `/songs/all/${username}`,
  GET_PLAYLIST: (username: string) => `/playlists/get/${username}`,
  GET_PLAYLIST_BY_ID: (id: string) => `/playlists/${id}`,
  GET_SONG: (id: string) => `/songs/${id}`,
  UPDATE_SONG_LIKE: (id: string) => `/songs/like/${id}`,
  UPDATE_SONG_DISLIKE: (id: string) => `/songs/dislike/${id}`,
  UPDATE_PLAYLIST_LIKE: (id: string) => `/playlists/like/${id}`,
  UPDATE_PLAYLIST_DISLIKE: (id: string) => `/playlists/dislike/${id}`,
  USERS_INFO: (username: string) => `/users/info/${username}`,
}
