export const songsGenres = [
  'Pop',
  'Rock',
  'Hip-Hop',
  'Rap',
  'R&B',
  'Jazz',
  'Blues',
  'Soul',
  'Funk',
  'Disco',
  'Country',
  'Reggae',
  'Ska',
  'Metal',
  'Punk',
  'Grunge',
  'Alternative',
  'Indie',
  'Folk',
  'Electronic',
  'House',
  'Techno',
  'Trance',
  'Dubstep',
  'Drum and Bass',
  'Ambient',
  'Classical',
  'Opera',
  'Orchestral',
  'Soundtrack',
  'Gospel',
  'Christian',
  'Latin',
  'Salsa',
  'Bachata',
  'Reggaeton',
  'Flamenco',
  'K-Pop',
  'J-Pop',
  'C-Pop',
  'Afrobeat',
  'Dancehall',
  'Trap',
  'Lo-Fi',
  'Synthwave',
  'Industrial',
  'Experimental',
  'Post-Rock',
  'Shoegaze',
  'Hardcore',
  'Emo',
  'New Wave',
  'Bluegrass',

  'Heavy Metal',
  'Thrash Metal',
  'Death Metal',
  'Black Metal',
  'Doom Metal',
  'Power Metal',
  'Symphonic Metal',
  'Progressive Metal',
  'Nu Metal',
  'Metalcore',
  'Post-Metal',
  'Sludge Metal',
  'Folk Metal',
  'Viking Metal',
  'Glam Metal',

  'Hard Rock',
  'Psychedelic Rock',
  'Garage Rock',
  'Progressive Rock',
  'Post-Punk',
  'Art Rock',
  'Math Rock',
  'Southern Rock',
  'Soft Rock',
  'Gothic Rock',
  'Stoner Rock',

  'Chillout',
  'Deep House',
  'Electro House',
  'Minimal Techno',
  'Hardstyle',
  'Breakbeat',
  'Glitch',
  'Future Bass',
  'Vaporwave',
  'Chiptune',
  'Eurodance',
  'Jungle',
  'Gabber',
  'Bounce',
  'Synthpop',

  'Merengue',
  'Cumbia',
  'Tango',
  'Mambo',
  'Mariachi',
  'Ranchera',

  'Celtic',
  'Native American',
  'African Traditional',
  'Middle Eastern',
  'Indian Classical',
  'Chinese Traditional',
  'Japanese Traditional',
  'Persian',
  'Gamelan',
  'Tuvan Throat Singing',

  'Swing',
  'Bebop',
  'Cool Jazz',
  'Free Jazz',
  'Fusion',
  'Latin Jazz',
  'Smooth Jazz',
  'Gypsy Jazz',
  'Acid Jazz',

  'Boom Bap',
  'Trap',
  'Mumble Rap',
  'G-Funk',
  'Old School Hip-Hop',
  'New School Hip-Hop',
  'Alternative Hip-Hop',
  'Conscious Hip-Hop',
  'Gangsta Rap',
  'Cloud Rap',

  'Drone',
  'Noise',
  'Darkwave',
  'Neoclassical',
  'Avant-Garde',
  'Krautrock',
  'Post-Hardcore',
  'Screamo',
  'Crust Punk',
  'Hardstyle',
  'Speedcore',
  'Breakcore',
  'Sound Collage',
  'Musique Concrète',
]
